version: '3.7'

services:
  database:
    image: mysql:8.0
    ports:
      - "18200:3306"
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Linhty@1802
      MYSQL_DATABASE: mt-store
      MYSQL_USER: tuannq
      MYSQL_PASSWORD: Linhty@1802
      MYSQL_ROOT_HOST: '%'
volumes:
  database_data: